/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexPermGroup.Blocks.Primitive
public import HexPermGroup.Blocks.Action
public import HexPermGroup.Blocks.Size
public import HexPermGroupMathlib.Action
public import Mathlib.Data.Setoid.Basic

public section

namespace Hex.PermGroup

/-- Computational block invariance agrees with preservation by every
permutation in the Mathlib subgroup generated by the original input. -/
theorem Partition.invariant_spec (p : Partition n) (G : Group n) :
    p.IsInvariant G ↔ ∀ g ∈ closure G.generators, ∀ x y,
      p.toSetoid x y ↔ p.toSetoid (g x) (g y) := by
  constructor
  · intro h g hg x y
    change p.Same x y ↔ p.Same (g x) (g y)
    have hm : Generated G.generators (Perm.ofEquiv g) :=
      generated_iff_mem.mpr (by simpa using hg)
    simpa only [Perm.get_ofEquiv] using h (Perm.ofEquiv g) hm x y
  · intro h g hg x y
    exact h g.toEquiv (generated_iff_mem.mp hg) x y

/-- The result is the least invariant Mathlib equivalence relation containing
the seeds. This includes its admissibility, not merely a one-sided bound. -/
theorem Group.blocks_spec (G : Group n) (pairs : List (Fin n × Fin n)) :
    IsLeast {r : Setoid (Fin n) |
      (∀ g ∈ closure G.generators, ∀ x y, r x y → r (g x) (g y)) ∧
        ∀ q ∈ pairs, r q.1 q.2} (G.blocks pairs).toSetoid := by
  constructor
  · refine ⟨?_, G.blocks_seeds pairs⟩
    intro g hg x y hxy
    exact (((G.blocks pairs).invariant_spec G).mp (G.blocks_invariant pairs) g hg x y).mp hxy
  · intro r hr x y hxy
    exact G.blocks_least pairs r.r r.iseqv
      (fun g hg a b => hr.1 g.toEquiv (generated_iff_mem.mp hg) a b) hr.2 x y hxy

/-- Minimality identifies the executable result with the infimum of all
admissible equivalence relations in Mathlib's complete lattice. -/
theorem Group.blocks_sInf (G : Group n) (pairs : List (Fin n × Fin n)) :
    (G.blocks pairs).toSetoid = sInf {r : Setoid (Fin n) |
      (∀ g ∈ closure G.generators, ∀ x y, r x y → r (g x) (g y)) ∧
        ∀ q ∈ pairs, r q.1 q.2} :=
  (G.blocks_spec pairs).csInf_eq.symm

namespace BlockAction

variable {G : Group n} {p : Partition n} {hp : p.IsInvariant G}

/-- The homomorphism kernel fixes every block setwise, retaining the original
degree and allowing nontrivial permutations inside each block. -/
theorem mem_ker (a : BlockAction G p hp) (g : Element G) :
    g ∈ a.image.hom.ker ↔ ∀ x, p.toSetoid (g.val.toEquiv x) x :=
  (a.image.mem_ker g).trans (Action.blocks_fixed G p hp g)

theorem order_mul_image (a : BlockAction G p hp) :
    G.order = a.kernel.group.order * a.image.group.order :=
  a.kernel.order_mul_image a.image

end BlockAction

end Hex.PermGroup
