/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexPermGroup.Word
public import HexPermGroupMathlib.Perm
public import Mathlib.Algebra.Group.Subgroup.Lattice

public section

namespace Hex.PermGroup

/-- The mathematical subgroup generated by the converted original inputs. -/
@[expose] def closure (S : Array (Perm n)) : Subgroup (Equiv.Perm (Fin n)) :=
  Subgroup.closure {e | ∃ p ∈ S, p.toEquiv = e}

/-- Generated-subgroup semantics agrees with Mathlib subgroup closure. -/
theorem generated_iff_mem {S : Array (Perm n)} {p : Perm n} :
    Generated S p ↔ p.toEquiv ∈ closure S := by
  constructor
  · intro hp
    induction hp with
    | id => simp [closure]
    | generator hp => exact Subgroup.subset_closure ⟨_, hp, rfl⟩
    | comp _ _ hp hq => simpa using (closure S).mul_mem hp hq
    | inv _ hp => simpa using (closure S).inv_mem hp
  · intro hp
    have h : Generated S (Perm.ofEquiv p.toEquiv) := by
      generalize he : p.toEquiv = e at hp ⊢
      clear he
      induction hp using Subgroup.closure_induction with
      | mem e he =>
        rcases he with ⟨q, hq, rfl⟩
        simpa using Generated.generator hq
      | one => simpa using (Generated.id (S := S))
      | mul x y _ _ hx hy => simpa using Generated.comp hx hy
      | inv x _ hx => simpa using Generated.inv hx
    simpa using h

/-- A successfully replayed word proves membership in Mathlib's subgroup. -/
theorem checkWord_spec {S : Array (Perm n)} {p : Perm n} {program : Program}
    (h : checkWord S p program = true) : p.toEquiv ∈ closure S :=
  generated_iff_mem.mp (checkWord_sound h)

end Hex.PermGroup
